### ISSUE TITLE
Example ?

### ISSUE THREAD

**Issue by camilleeyries** [mafintosh/respawn#14]
Hi ! I know, I'm a noob.

Can you make a simple example pls ? I want to make a thing that make my script restart after some time...

**Comment by scippio** [comment]
If you need interval restarting, there is for example: https://www.npmjs.com/package/custodian .

**Comment by camilleeyries** [comment]
I already solved my issue with forever-monitor and process.exit(), but thx x) 😜👍👍🏻👍🏼👍🏽👍🏾👍🏿
