### ISSUE TITLE
Port in use

### ISSUE THREAD

**Issue by scippio** [mafintosh/respawn#17]
I used it for restify and getting:
```Error: listen EADDRINUSE```
after start respawn. When I start only "node server.js" everything is ok. Respawn creating childs? Maybe this is the problem... ?

**Comment by scippio** [comment]
Anybody here? :)

**Comment by AlexanderElias** [comment]
@scippio not to take away from mafintosh awesome project but i created a similar project. Try it out maybe that will help you. https://github.com/AlexanderElias/revive/

**Comment by mafintosh** [comment]
@scippio you'll need to provide a bit more context for me to look into that. do you have a runnable example or something?

**Comment by scippio** [comment]
Sorry I think I'm bad understand the Respawn functionality :) ... I use forever.js now :)

**Comment by mafintosh** [comment]
👍
