### ISSUE TITLE
Crash count is still wrong

### ISSUE THREAD

**Issue by Cap32** [mafintosh/respawn#19]
There are only two places may invoke `_crash()`: [L167](https://github.com/mafintosh/respawn/blob/7b899e7e22347bca9892f362005de40c45c855bd/index.js#L167) in `child.on('error')` and [L182](https://github.com/mafintosh/respawn/blob/7b899e7e22347bca9892f362005de40c45c855bd/index.js#L182) in `child.on('exit')` function handlers, but both of them will not invoke `loop()`, so once `_crash()` is invoked, child process will not restart anymore,  so `crashes` will never larger than `1`.

**Comment by mafintosh** [comment]
see the pr comment
